### ISSUE TITLE
Commands in Games Folder dont work

### ISSUE THREAD

**Issue by Nocturnal-Compiler** [DarkThunder99/150-Commands-Bot#3]
any command in game command dosent work it shows get is undefiled berfore get its games.ops #

**Comment by matsyui** [comment]
Helping a random person to my discord server, I think he is using your source code and I tried to check this out and yes its the same. There's currently error to your code which is:

`
C:\Users\XXXXXX\Desktop\150-Commands-Bot-main\node_modules\amethyste-api\src\main.js:16
        if (!token) throw new Error("Unknown Token: Token Missing");
                    
Error: Unknown Token: Token Missing
    at new ameClient (C:\Users\XXXXXX\Desktop\150-Commands-Bot-main\node_modules\amethyste-api\src\main.js:16:27)
    at Object.<anonymous> (C:\Users\XXXXXX\Desktop\150-Commands-Bot-main\commands\image\fire.js:4:16)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at load (C:\Users\XXXXXX\Desktop\150-Commands-Bot-main\handler\command.js:7:24)
    at C:\Users\XXXXXX\Desktop\150-Commands-Bot-main\handler\command.js:12:90
`

![image](https://user-images.githubusercontent.com/62344860/127771779-3d91e714-33a9-49cb-af28-b93ef07a51a2.png)
